[options]
automatic_update = true
colorscheme = 'onedark'
colorscheme_bg = 'dark'
enable_guicolors = true
statusline_separator = 'arrow'
statusline_iseparator = 'arrow'
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true
bootstrap_before = 'myspacevim#before'
bootstrap_after = 'myspacevim#after'
expand_tab = true
autocomplete_method = 'coc'
autocomplete_parens = false
filemanager = "defx"

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = 'complete'
auto_completion_tab_key_behavior = 'cycle'
auto_completion_complete_with_key_sequence = "C-<SPC>"

[[layers]]
name = 'incsearch'

[[layers]]
name = 'fuzzy'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30


[[layers]]
name = 'VersionControl'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'denite'

[[layers]]
name = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'format'

[[layers]]
name = 'lang#assembly'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#dart'

[[layers]]
name = 'lang#extra'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#ipynb'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#kotlin'

[[layers]]
name = 'lang#latex'

[[layers]]
name = 'lang#lua'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#matlab'

[[layers]]
name='lang#perl'

[[layers]]
name='lang#php'

[[layers]]
name='lang#python'
python_file_head = []
python_interpreter = '/usr/bin/python'
enable_typeinfo = true

[[layers]]
name='lang#rust'
recommended_style=true

[[layers]]
name='lang#sh'

[[layers]]
name='lang#toml'

[[layers]]
name='lang#vim'

[[layers]]
name='lang#xml'

[[layers]]
name='lsp'
filetypes = ['rust', 'python', 'c', 'cpp', 'objc', 'objcpp', 'sh']
[layers.override_cmd]
rust = ['rust-analyzer']

[[layers]]
name='checkers'

[[layers]]
name='sudo'

[[layers]]
name='tmux'

[[layers]]
name='tools'

[[custom_plugins]]
repo = "justinmk/vim-sneak"
